# Uncomment this line to define a global platform for your project
 platform :ios, '5.0'

target 'WeatherAPIKata' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WeatherAPIKata

  target 'WeatherAPIKataTests' do
    pod 'Kiwi'
  end

end
